### Recuperar todas las películas

GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las películas de un género
GET http://localhost:1234/movies?genre=action

### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "genre": ["Crime", "Drama"],
    "duration": 175,
    "poster": "https://pics.filmaffinity.com/El_padrino-757154190-large.jpg"
}

### Editar una parte de una película
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1909
}